// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy_1UOx1PU7y8yBIrN9gBO2B8OhK-YBUA',
    appId: '1:1060144138535:web:e95c9fcb9006b512460102',
    messagingSenderId: '1060144138535',
    projectId: 'biblioteca-ce264',
    authDomain: 'biblioteca-ce264.firebaseapp.com',
    storageBucket: 'biblioteca-ce264.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1llPwaL7QkA6Q-PyhGl8TvA7nmCaz1E8',
    appId: '1:1060144138535:android:dff56f2d4c5859e6460102',
    messagingSenderId: '1060144138535',
    projectId: 'biblioteca-ce264',
    storageBucket: 'biblioteca-ce264.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR7Xu6qRaHPxx9PnZD9stTvNmtbzdQHB8',
    appId: '1:1060144138535:ios:7f04f5f62393208e460102',
    messagingSenderId: '1060144138535',
    projectId: 'biblioteca-ce264',
    storageBucket: 'biblioteca-ce264.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR7Xu6qRaHPxx9PnZD9stTvNmtbzdQHB8',
    appId: '1:1060144138535:ios:7f04f5f62393208e460102',
    messagingSenderId: '1060144138535',
    projectId: 'biblioteca-ce264',
    storageBucket: 'biblioteca-ce264.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy_1UOx1PU7y8yBIrN9gBO2B8OhK-YBUA',
    appId: '1:1060144138535:web:176299a0a0b4b1ce460102',
    messagingSenderId: '1060144138535',
    projectId: 'biblioteca-ce264',
    authDomain: 'biblioteca-ce264.firebaseapp.com',
    storageBucket: 'biblioteca-ce264.firebasestorage.app',
  );
}
